# Setup
title: Mapping Slavery in Germany
tagline: "A New Mapping Project"
description: "This project is produced by Dr. Wendy-Lou Sutherland, Associate Professor of German, Black European and Diaspora Studies, and Cal Murgu, Digital Humanities Librarian."
url:
baseurl: "ncflib.github.com"
paginate: 5
permalink: pretty

# About/contact
author:
  name: Cal Murgu
  url: https://twitter.com/calmurgu
  email: cmurgu@ncf.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
